modLoader="javafml"
loaderVersion="[46,)"
license="${mod_license}"
[[mods]]
modId="frameshifted"
version="1.0
displayName="Ad Astra: Frame Shifted"
authors="Destiny"

description='''${mod_description}'''
[[dependencies.frameshifted]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.frameshifted]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"