modLoader="javafml"
loaderVersion="[46,)"
license="${mod_license}"
[[mods]]
modId="ad_astra_frame_shifted"
version="1.0"
displayName="Ad Astra: Frame Shifted"
authors="Destiny"

description='''${mod_description}'''
[[dependencies.ad_astra_frame_shifted]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ad_astra_frame_shifted]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.ad_astra_frame_shifted]]
    modId="ad_astra"
    mandatory=true
    versionRange="[4.4.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ad_astra_frame_shifted]]
    modId="alexscaves"
    mandatory=false
    versionRange="[1.0.9,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ad_astra_frame_shifted]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ad_astra_frame_shifted]]
    modId="resourceful_lib"
    mandatory=true
    versionRange="[2.1.21,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ad_astra_frame_shifted]]
    modId="resourceful_config"
    mandatory=true
    versionRange="[2.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ad_astra_frame_shifted]]
    modId="botarium"
    mandatory=true
    versionRange="[2.3.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ad_astra_frame_shifted]]
    modId="citadel"
    mandatory=true
    versionRange="[2.4.7,)"
    ordering="NONE"
    side="BOTH"